In [13]:
a = [1,2,3,4]
print(a)

[1, 2, 3, 4]


In [8]:
type(a)

list

In [9]:
import numpy as np

In [16]:
n_a = np.array(a, dtype='int16')
print(n_a)
print(type(n_a))
print(n_a.ndim)
print(n_a.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)


In [11]:
# 2d-array
b = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
print(b.dtype)

int64


In [18]:
print(n_a.dtype)

int16


In [19]:
print(b.nbytes)

64


In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [23]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(4,5)*10

array([[2.62133433e-01, 8.54232310e+00, 1.62486014e+00, 6.78633587e+00,
        9.84611025e-01],
       [9.80924442e+00, 2.20354538e-01, 3.63276980e+00, 5.01982793e+00,
        8.57660352e+00],
       [9.68706186e-03, 9.01111964e+00, 2.87134196e+00, 3.39689368e+00,
        1.11227991e+00],
       [7.61523835e+00, 1.89855680e+00, 3.04566392e+00, 2.15997523e+00,
        5.23810713e+00]])

In [29]:
a = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
a.shape

(3, 2)

In [31]:
a[a>2]

array([3, 4, 5, 6])

In [32]:
filt = (a>2) & (a<5)
a[filt]

array([3, 4])